name: MarkDartix
description: MarkDartix
publish_to: none
version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    assets:
        - assets/icons/undraw_content.svg
  args: ^2.3.1
  source_maps: ^0.10.10
  platform: ^3.1.0
  path_provider: ^2.0.7
  hive: ^2.1.1
  hive_flutter: ^1.2.0
  path_provider: ^3.0.3
  image_picker: ^0.8.5
  charset_converter: ^2.0.0
  keyboard_info: ^1.0.2
  path_provider: ^2.0.8
  file: ^6.1.2
  keyboard_shortcuts: ^2.1.1
  in_app_update: ^2.0.1
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.22
  fuzzy: ^0.2.0
  file: ^6.1.2
  process_run: ^1.2.2
  pubspec_yaml: ^1.0.0
  license_checker: ^2.0.0
  path: ^1.8.1
  flutter_file_dialog: ^1.4.4
  http: ^0.13.3
  flutter_svg: ^0.23.0+1
  clipboard: ^0.1.2+8

dev_dependencies:
  build_runner: ^2.3.0
  copy_with_extension_gen: ^4.0.4
  flutter_driver:
    sdk: flutter
  flutter_gen_runner: ^5.0.3
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.1
  mockito: any
  msix: ^3.7.0
  source_gen: ^1.2.6
  test: any

flutter_gen:
  output: lib/generated/assets/

flutter:
  generate: false
  uses-material-design: true

flutter_intl:
  enabled: true

